### ISSUE TITLE
Strange line in effects section

### ISSUE THREAD

**Issue by jarmush** [CleverRaven/Cataclysm-DDA#10882]
When i play Cataclysm in russian strange line "Project-ID-Version" appears in effects section
![rus](https://cloud.githubusercontent.com/assets/6452938/5753985/29136204-9ca3-11e4-8800-01b3813606be.png)

When english language selected everything is OK
![eng](https://cloud.githubusercontent.com/assets/6452938/5753990/3d694c32-9ca3-11e4-8d69-54129da1d35d.png)

**Comment by narc0tiq** [comment]
Looks like a string leak from somewhere, possibly something to do with the Russian .po. [Peeking at it](https://raw.githubusercontent.com/CleverRaven/Cataclysm-DDA/master/lang/po/ru.po), the first few strings are:

```
msgid ""
msgstr ""
"Project-Id-Version: Cataclysm-DDA\n"
```

Of note, the current translation says "POT-Creation-Date: 2015-01-12 12:51+0300\n", which makes it certainly more recent than the pictured 2014-12 -- the issue may have been fixed already. I certainly couldn't reproduce it by setting my language to Russian on Linux/Curses.

**Comment by BevapDin** [comment]
This is caused by an empty string being translated. effect::disp_name()` (which is used to get the displayed effect names) does not check for the name being empty and always applies the translation macro (even to empty strings). effects.json has several effects without name, through I don't know whether the player character can get those.

**Comment by jarmush** [comment]
Tried latest 2641 build, bug still there
![latest](https://cloud.githubusercontent.com/assets/6452938/5754616/3492376e-9cac-11e4-91e7-2197e92eeb2c.png)

**Comment by narc0tiq** [comment]
Must be the empty-named effect, then. Thanks for reporting in.

**Comment by swwu** [comment]
Can we fix this by

**Comment by swwu** [comment]
(Woops wrong button)

This seems like it'd be a straightforward fix if we just don't display ""-named effects in the effects menu. I'll look into it.

**Comment by KA101** [comment]
Cropping up in Italian as well: http://smf.cataclysmdda.com/index.php?topic=8336.msg213156#msg213156

**Comment by swwu** [comment]
So the status screen actually filters out empty string effects: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/player.cpp#L2341

This is definitely an issue with the translation portion ("" being translated to those strings BEFORE it can be filtered out), and I presume that all data files that have a value of "" will have their values transformed to "POT-Creation-Date" gibberish post-translation.

Maybe the solution is to explicitly add a translation of "" -> "" to all language files? I unfortunately have no idea how the translations work under the hood.

**Comment by BevapDin** [comment]
> "POT-Creation-Date" gibberis

This gibberish contains various information used by and for the translation system, including rules for plural form. See  https://www.gnu.org/software/gettext/manual/html_node/Header-Entry.html Clients are not supposed to translate the empty string, this is documented behavior.

**Comment by swwu** [comment]
@BevapDin would the correct fix just be changing the translation macro?

**Comment by BevapDin** [comment]
The correct fix seems to not translate empty strings at all.

**Comment by narc0tiq** [comment]
Yes. That's what I thought, as well.
