### ISSUE TITLE
Some tilesets can't be loaded when PREFIX is defined

### ISSUE THREAD

**Issue by akien-mga** [CleverRaven/Cataclysm-DDA#12800]
Hi there,

I'm working on packaging Cataclysm DDA 0.C for Mageia, so I install it system-wide in the `/usr` prefix.

It's worth noting that I'm putting the game data in `/usr/share/games/cataclysm-dda`, so I patched https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/path_info.cpp#L114 and https://github.com/CleverRaven/Cataclysm-DDA/blob/master/Makefile#L494 to add "games/" in the hardcoded path, but those changes should not trigger the issue I'm seeing.

When selecting some tilesets (I'll give the list thereafter), I get:
![ivc1](https://cloud.githubusercontent.com/assets/4701338/8396375/86ac0936-1da2-11e5-8ca2-e8d966b8922d.jpg)

The problematic tilesets are:
- Blockhead's
- Deon's
- Hoder's
- Thuztor'@
- Tsu's

After some digging in the code, I found that the problematic concatenation happens here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/cata_tiles.cpp#L177-L179
`FILENAMES["datadir"]` is `/usr/share/games/cataclysm-dda/` as expected, so the problem comes from the `img_path`.

Looking at the different tile_config.json files of the tilesets, it seems that:
- The tilesets that are working define a relative "file" path, as in https://github.com/CleverRaven/Cataclysm-DDA/blob/master/gfx/RetroASCIITileset/tile_config.json#L11
- The tilesets that do not work have no "file" path defined, so I guess the code generates an absolute file path based on the `TILESET` field in tileset.txt. See e.g. https://github.com/CleverRaven/Cataclysm-DDA/blob/master/gfx/HoderTileset/tile_config.json

So a workaround for this issue is to add a "file" path in all tileset_config.json files, but there might also be a better way to fix it in the code (e.g. by reviewing the path that generates the absolute file path to the tileset instead of a relative one).
##

**Comment by DavidKeaton** [comment]
The path prefix path is being applied twice...? Why?

**Comment by akien-mga** [comment]
> The prefix path is being applied twice...? Why?

Looking further at the code, it looks like:
* Tilesets with a "file" definition (the working ones) have their path retrieve here: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/cata_tiles.cpp#L296
* Tilesets without a "file" definition use the fallback method: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/cata_tiles.cpp#L321
  * The tileset_path that it uses comes from get_tile_information: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/cata_tiles.cpp#L98
  * And in get_tile_information, the absolute path is set as a prefix here: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/cata_tiles.cpp#L156

**Comment by akien-mga** [comment]
This patch seems to fix the issue:
```
--- Cataclysm-DDA-0.C/src/cata_tiles.cpp.old    2015-06-28 15:27:40.329083005 +0200
+++ Cataclysm-DDA-0.C/src/cata_tiles.cpp        2015-06-28 15:30:21.322145264 +0200
@@ -146,7 +146,7 @@
                     dbg( D_INFO ) << "JSON path set to [" << json_path << "].";
                 } else if (sOption.find("TILESET") != std::string::npos) {
                     fin >> tileset_path;
-                    tileset_path = FILENAMES["gfxdir"] + tileset_path;
+                    tileset_path = "gfx/" + tileset_path;
                     dbg( D_INFO ) << "TILESET path set to [" << tileset_path << "].";
                 }
             }
```

You might want to define "gfx/" as FILENAMES["gfx"] in src/path_info.cpp though to prevent hardcoding it in src/cata_tiles.cpp.

Note that there are already occurrences of FILENAMES["gfx"] in src/path_info.cpp, but it looks like this value not defined anywhere. https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/path_info.cpp#L92-L93

**Comment by akien-mga** [comment]
Another possibility, maybe cleaner:
* Drop the prefix-specific code that adds the datadir as a prefix: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/cata_tiles.cpp#L177-L179
* Add the prefix in the "new format" method too: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/cata_tiles.cpp#L296

So as a patch:
```
--- Cataclysm-DDA-0.C/src/cata_tiles.cpp.old    2015-06-28 15:27:40.329083005 +0200
+++ Cataclysm-DDA-0.C/src/cata_tiles.cpp        2015-06-28 15:38:14.490150892 +0200
@@ -167,10 +167,6 @@
 int cata_tiles::load_tileset(std::string path, int R, int G, int B)
 {
     std::string img_path = path;
-#ifdef PREFIX   // use the PREFIX path over the current directory
-    img_path = (FILENAMES["datadir"] + "/" + img_path);
-       std::cout << path << "\n" << FILENAMES["datadir"] << std::endl;
-#endif
     /** reinit tile_atlas */
     SDL_Surface *tile_atlas = IMG_Load(img_path.c_str());
 
@@ -286,7 +282,7 @@
         JsonArray tiles_new = config.get_array("tiles-new");
         while (tiles_new.has_more()) {
             JsonObject tile_part_def = tiles_new.next_object();
-            const std::string tileset_image_path = tile_part_def.get_string("file");
+            const std::string tileset_image_path = FILENAMES["datadir"] + tile_part_def.get_string("file");
             int R = -1;
             int G = -1;
             int B = -1;
```

I've tested both patches, and they work fine (I can load both "new" and "old format" tilesets, and they display fine in game as far as I can tell). Some reviewing by someone who knows the codebase better might be useful though :)

I can do a pull request if you like any of the two proposals.

**Comment by akien-mga** [comment]
Ah actually the second proposal might be problematic in builds without PREFIX defined, as in such cases the ```gfx``` folder is not in FILENAMES["datadir"]: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/path_info.cpp#L118-L120

**Comment by akien-mga** [comment]
> Ah actually the second proposal might be problematic in builds without PREFIX defined, as in such cases the gfx folder is not in FILENAMES["datadir"]

Maybe a FILENAMES["basedatadir"] folder needs to be added that would be a copy of FILENAMES["datadir"] on system install and would be "." for the rest?

**Comment by VlasovVitaly** [comment]
> Edit: Or mimic the behaviour of the old format, so use FILENAMES["gfxdir"] as a prefix, and remove "gfx/" from the "file" entry in new json files.

This is only right way. Tiles author's shouldn’t think about filepaths, game must care about it. All paths must be relative.

**Comment by DavidKeaton** [comment]
was this fixed with my recent patch?

**Comment by VlasovVitaly** [comment]
Give PR link, please.

I tested TILES install build with tiles. Still loading error, but i don't know where is error: in tiles config or in cmake paths.

**Comment by DavidKeaton** [comment]
PR #12993

**Comment by VlasovVitaly** [comment]
Hmm...
Tiles configs already contain relative paths. That's good.
Your fix related to Makefile. I was talking about cmake builds.
But i still get error's with your fix. To closer look i need to get my home PC cuz PC on work is suck. Tired to wait infinitive compilation............

On firsts look.
with ```make RELEASE=1 TILES=1 PREFIX=/opt``` it install gfx into PREFIX/share/cataclysm-dda/gfx. That is right. But it look gfx in PREFIX/gfx. That is wrong.

**Comment by DavidKeaton** [comment]
Ah lame. I would run a `git blame` to narrow down the offending commit to see where else the changes need to be made, but am at work.

**Comment by VlasovVitaly** [comment]
> am at work.

+

**Comment by macrosblackd** [comment]
@VlasovVitaly - if you're using PREFIX and release and are wanting gfx to be in the PREFIX/share/cataclysm-dda/ path, then you need to use DATA_DIR_PREFIX=/opt instead of PREFIX.

**Comment by VlasovVitaly** [comment]
DATA_DIR_PREFIX is flag. This var does not accept args.

**Comment by VlasovVitaly** [comment]
Ok. Guess i know how to fix that(with pain).

Old-style configs is working with correct PREFIX.
To support new-style we can use @akien-mga path.
```
int cata_tiles::load_tileset(std::string path, int R, int G, int B)
-//#ifdef PREFIX   // use the PREFIX path over the current directory
-//    img_path = (FILENAMES["base_path"] + "/" + img_path);
-//#elif defined DATA_DIR_PREFIX // Used for linux release installs
-//    img_path = (FILENAMES["datadir"] + "/" + img_path);
-//#endif
```
Btw, i'ts very bad idea to manipulate paths in load_tileset(). load_tileset() should just load tileset, nothing more.
```
void cata_tiles::load_tilejson_from_file
-            const std::string tileset_image_path = tile_part_def.get_string("file");
+            const std::string tileset_image_path = FILENAMES["gfxdir"] + tile_part_def.get_string("file");
```

But every new tileset config must be changed. Leading "gfx" must be removed from tiles path.
This tilessets should be changed:
ChestHole*
MShock24*
RetroTileset*

It's possible to use VERY DIRTY HACK without changing tilesets configs:
```
void cata_tiles::load_tilejson_from_file
-            const std::string tileset_image_path = tile_part_def.get_string("file");
+            const std::string tileset_image_path = FILENAMES["gfxdir"] + "../" + tile_part_def.get_string("file");
```
This is very wrong. I won't do it!

So, i am waiting for PR #13047 to apply this.

**Comment by narc0tiq** [comment]
> But every new tileset config must be changed. Leading "gfx" must be removed from tiles path.

So... three tilesets, which should never even have had any internal knowledge of a directory named "gfx". I'm okay with this.

**Comment by VlasovVitaly** [comment]
Sad but not tree. Actually is 10. I added asterisk at end of names. It's tree authors.

**Comment by narc0tiq** [comment]
Ugh. This is how legacy code gets started. `if(datadir.startsWith("gfx")) { datadir = datadir.Substring(4); }`... let's not do that.

Really, `gfx` is not a part of the path that tilesets should be aware of, precisely because it might change. Maybe tomorrow we'll want the directory to be called "tilesets" or "graphics sets" or whatnot. 

On a similar note, the tilesets should also be unaware of the name of the directory they live in -- if I want to rename "MShock32TilesetModded" to "MyLittlePonySet", that should be as simple as renaming the directory, period. It should most definitely not require me to go into its `tile_config.json` **and** its `tileset.txt` to do a search-and-replace.

**Comment by VlasovVitaly** [comment]
> Really, gfx is not a part of the path that tilesets should be aware of, precisely because it might change. Maybe tomorrow we'll want the directory to be called "tilesets" or "graphics sets" or whatnot. 

Yes. We have FILENAMES["gfxdir"] for that.

> On a similar note, the tilesets should also be unaware of the name of the directory they live in -- if I want to rename "MShock32TilesetModded" to "MyLittlePonySet", that should be as simple as renaming the directory, period. It should most definitely not require me to go into its tile_config.json and its tileset.txt to do a search-and-replace.

Yes. May be. This can be realized.
I see this like that...
Add new var FILENAMES["tileset-conf"] with value: "tileset.txt". This var is hardcoded into source. When game need to load tiles with some name it will look recursive in all files with name FILENAMES["tileset-conf"] in FILENAMES["gfxdir"]. tileset-conf must contain name and json values (optional tiles path). All paths must be relative(may be with subdirs inside this tileset dir). Author only need to properly setup tileset name and json-config filename into tileset.txt. This loading system not depend on directory name but you still need edit FILENAMES["tileset-conf"] to rename tileset.

This behaviour touch different parts of game and can't be done easily.

**Comment by DavidKeaton** [comment]
You mean just for each directory, yes? Also a define would prob suffice instead of another `FILENAMES` entry.

**Comment by narc0tiq** [comment]
> new var FILENAMES["tileset-conf"]

Purely to avoid repeating the string literal `"tileset.txt"`, I imagine?

> All paths must be relative

To clarify, this means paths must be relative to the tileset.txt. I'd also discourage (but not disallow) using `../` to try to reference another existing tileset (which may or may not exist).

> you still need edit [tileset.txt] to rename tileset.

Yes, and that's to be expected since that's the authoritative source for the tileset's name (both internal and display name). What should not be present in the file is the name of the directory the tileset lives in, as we just discussed.

**Comment by narc0tiq** [comment]
Incidentally, it looks like `cata_tiles::get_tile_information` already mostly does the right thing here and only needs to add the current directory name to things like `json_path = FILENAMES["gfxdir"] + json_path;`. I haven't read it closely enough to be sure it's all sane, though.

**Comment by VlasovVitaly** [comment]
> You mean just for each directory, yes? Also a define would prob suffice instead of another FILENAMES entry.

May be i don't get your ask...
I mean Universal tileset loading algorithm.
1. Get tilseset name from options.
2. Move into directory where all tilesets are stored(FILENAMES["gfxdir"], each tileset in own directory. Directory name can be random.
3. Look all files with name FILENAMES["tileset-conf"](tileset.txt). Find NAME value in than files.
4. When Options name and tileset.txt name will be equal - load .json and .jpg by filename related to found dir.
???
5. PROFIT.

> Purely to avoid repeating the string literal "tileset.txt", I imagine?

Yeah. Occam's razor? Nothing hear about this...

> To clarify, this means paths must be relative to the tileset.txt. I'd also discourage (but not disallow) using ../ to try to reference another existing tileset (which may or may not exist).

Yes.

**Comment by narc0tiq** [comment]
> Look all files with name FILENAMES["tileset-conf"]

About that -- since you have to build a list of tile sets at start anyway (to populate the possible values for `OPTIONS["TILES"]`; this is done in `initOptions()` in `options.cpp`), why not also build up (at the same time) an `std::map<string,string> tileset_paths` where `tileset_paths[tileset_name] == "/where/it/is/on/disk"`?

That saves you the directory scan every time you have to find the current tile set by leveraging an action that was already happening regardless.

**Comment by DavidKeaton** [comment]
```
tiles/
|----MShock/
|     |---tileset.conf
|     |--- ...
|----RetroDays/
|     |---tileset.conf
|     |--- ...
| ...
```
That's what I meant I guess.

**Comment by VlasovVitaly** [comment]
> About that -- since you have to build a list of tile sets at start anyway (to populate the possible values for OPTIONS["TILES"]; this is done in initOptions() in options.cpp), why not also build up (at the same time) an std::map<string,string> tileset_paths where tileset_paths[tileset_name] == "/where/it/is/on/disk"?

Great. I didn't know about this. I will do it.

@DavidKeaton Something like that.

**Comment by chaosvolt** [comment]
Why am I always the last to notice these things? I'm hoping the Modded MShock is unaffected at least.

> On a similar note, the tilesets should also be unaware of the name of the directory they live in -- if I want to rename "MShock32TilesetModded" to "MyLittlePonySet", that should be as simple as renaming the directory, period. It should most definitely not require me to go into its tile_config.json and its tileset.txt to do a search-and-replace.

That would be hilarious. I was tempted to rename the Modded MShock tilesets, but if I went with the obvious name (Chaosvolt's) that would push it into the default slot due to alphanumeric sorting. And unlike Chezzo, I'm a bit reluctant to do that. XP

**Comment by narc0tiq** [comment]
Uh, the default tileset is determined by the value passed to `cOpt()` in
`options.cpp`, and is currently `"ChestHole"`. Alphabetical sorting only
means that `Chaosvolt's` would be to the left of the default (or past
wrap-around to the right).

**Comment by chaosvolt** [comment]
Oh. Doh. That actually seems like a saner idea than alphabetic default-picking. Dunno why I thought it'd use that sorting method.

Especially as I just realized that I could've sworn there was a "Blockhead" set that would be the default if it worked that way.

**Comment by VlasovVitaly** [comment]
Was fixed. Can be closed.
