### ISSUE TITLE
Smoke from vehicle does not dissperse

### ISSUE THREAD

**Issue by stk2008** [CleverRaven/Cataclysm-DDA#17669]
Windows 10 x64bit
CDDA 5233 x64bit tiles

Hi all basically if im driving my vehicle as per pic

[img]http://i.imgur.com/5Rj0MvC.png[/img]

you can see on the right is smoke following the road this is the route I took a while ago.
on my way back its still there.

Also I have noticed if I am going about 30MPH north or south smoke will start to render in front at the edge of the screen.

**Comment by Vidiveni** [comment]
Should be fixed in 5234 already but the build is broken atm so we can't update yet.

**Comment by TheWebfrog** [comment]
Yep happened to me too, same problem almost exactly

**Comment by mugling** [comment]
Closing this as a number of recent changes were made to `master` and there has been some latency in player feedback due to various buildbot failures. Please re-open if reproducible in `master`

**Comment by Grelko** [comment]
stk2008 said "Also I have noticed if I am going about 30MPH north or south smoke will start to render in front at the edge of the screen."

This is still happening in 6260 
http://imgur.com/a/5BiHL

**Comment by kevingranade** [comment]
On Feb 22, 2017 6:36 PM, "Grelko" <notifications@github.com> wrote:

stk2008 said "Also I have noticed if I am going about 30MPH north or south
smoke will start to render in front at the edge of the screen."

This is still happening in 6260
http://imgur.com/a/5BiHL

Are you sure it's not just smoke from a previous trip?

**Comment by Headjack** [comment]
Bumping this, it is smoke from a previous trip, but that is itself a bug, since the smoke should have long since disappeared.

**Comment by Night-Pryanik** [comment]
That's not a bug, but a feature of the game mechanics.

**Comment by kevingranade** [comment]
Smoke from a previous trip is a bug.

**Comment by Night-Pryanik** [comment]
But isn't this happening because of our reality bubble mechanics? Car generated smoke in some location, player then moves to the other location, RB moves with him, smoke in the previous location (outside of the current RB) stops processing.

**Comment by kevingranade** [comment]
Just because it's acting like you expect it to doesn't mean it's not a bug.
