### ISSUE TITLE
Greenery a little too durable?

### ISSUE THREAD

**Issue by Regularitee** [CleverRaven/Cataclysm-DDA#19571]
I've been driving around a 19-ton APC (yes, you read that correctly) with a somewhat underpowered engine (V6 gasoline) that can hit around 32 km/h or 20 mph. Now, it consistently fails to ram through more than one shrub at a time due to speed loss which I find very unlikely... but in theory possible under less-than-ideal circumstances.

However, this same 19-ton vehicle managed to be brought to a complete stop from a speed of 22 km/h (~14 mph) by, of all things, a datura flower. Not even a sapling, but a **flower**. A flower stopped a 19-ton vehicle.

I'm starting to think there's something broken when it comes to the game's ability to account for mass in collisions.

**Comment by mugling** [comment]
Long-standing issue. We fixed the damage caused by such collisions a while back but obviously not the slowdown part

**Comment by mugling** [comment]
What needs to happen is that collisions should reduce momentum and not velocity. Riding a bike into a bush is going to cause problems that wouldn't exist for a tank

**Comment by Regularitee** [comment]
Well, to start, I would recommend the "datura" probably shouldn't even qualify as a collidable object in the first place, since googling images brings up flowers. 

![image](https://cloud.githubusercontent.com/assets/8593513/20813981/1370cc9e-b7d5-11e6-8a21-9dc468cdc547.png)

As for the momentum and mass thing, that's a much bigger issue that still remains.

**Comment by LordZanos** [comment]
Datura probably shouldn't, but I think it's still an issue when my 25 ton APC with a v12 engine going at 40mph is stopped when it's composite rams collide with a shrub.

**Comment by Aivean** [comment]
I also think that ramming shrubs/trees/cars/houses should not damage armored vehicle that much. 

Check these videos:
http://www.liveleak.com/view?i=6de_1312742692
https://www.youtube.com/watch?v=fReXK_ntOYg

I understand that this may be game balance issue, but endgame is easy anyway. Why not allow player to craft thick steel plates that are designed to be rammed through things without being damaged?

**Comment by BorkBorkGoesTheCode** [comment]
A squirrel damaged my APC while I was traveling at 40mph.

**Comment by Rivet-the-Zombie** [comment]
Datura *can* grow into sizeable bushes, but it's definitely not going to stop a vehicle.

**Comment by Rivet-the-Zombie** [comment]
Datura *can* grow into a sizeable bush, but it's definitely not going to stop a vehicle.

**Comment by keyspace** [comment]
Hotfix proposed above.

**Comment by keyspace** [comment]
As [demonstrated](https://github.com/CleverRaven/Cataclysm-DDA/pull/19974#issuecomment-272746901) in #19974 (closed un-merged), this has been alleviated by VPO revert.

Are there cases where this is still present?
