### ISSUE TITLE
Assorted string issues

### ISSUE THREAD

**Issue by Wuzzy2** [CleverRaven/Cataclysm-DDA#23428]
Game version: ae5bdc036830b3c950337526d0870ec45489bd7d

Operating system: GNU/Linux

Tiles or curses: curses

Mods active: N/A

### Summary

There are some string issues.

* In the new player menu > Scenario tab, there's this text “Sort by:”. But it seems the position of “Press s to Change” is hardcoded. This means it'll overwrite the text before, this is especially a problem in translations, like the German one. In German, the sort type (points or alphabtical) is made completely invisible by this!

* In the player info menu in the game (`@` key): Select “Dexterity”. The English string for throwing penalty is too long and doesn't fit into the window.

* In the settings, if you change the default character name, the pop-up window is always in English.

**Comment by Night-Pryanik** [comment]
> Automatic line break in mod descriptions don't always work

What mods causes this behavior?

**Comment by Wuzzy2** [comment]
It's not a mod issue, it's an issue with how the main menu fails to render mod descriptions correctly.

Try with German (pull `.po` from Transifex), then just scroll down the mod list. For some mods, the automatic line break works, for some mods, it doesn't:

* Behelfsmäßige-Dinge-Mod
* Erweiterte Realistische Waffen
* Generische Feuerwaffen
* Mehr Überlebenswerkzeuge
* Waffenfertigungspaket
* Alternative Kartenlegende
* Mehr Orte
* Fahrzeugextras-Paket
* Panzer und andere Fahrzeuge

**Comment by Leland** [comment]
>  Walk on a battery: “You see here 100 batterys.”

This should have been fixed by #23418, can you double check that it has?

**Comment by Night-Pryanik** [comment]
> it's an issue with how the main menu fails to render mod descriptions correctly.

It's an issue of our UI was designed for 80x24, so long descriptions just don't fit in the tiny window.

**Comment by Wuzzy2** [comment]
@Night-Pryanik: There's at least one “free” line left for use:

https://lut.im/DXFlcRzgJo/nh4yxt0Ky8Rh7uL4.png

**Comment by Night-Pryanik** [comment]
Sure, we could use this "free" line, but what if description is large enough to take up its original lines plus this "free" line, and is asking for more? We need a total rework of the UI with windows taking all available space and scrollbars.

**Comment by Wuzzy2** [comment]
>> Walk on a battery: “You see here 100 batterys.” 

> This should have been fixed by #23418, can you double check that it has?

It's not really fixed. Now it's “You see here 100 battery”. When I put down 2 batteries (from debug menu), it's “200 battery”.

Meh.

45b804c42012a3b4c30bfc6771ab6f5540044ae2

**Comment by illi-kun** [comment]
> Automatic line break in mod descriptions don't always work

Please provide an example for UI issues. It helps much more than plain text.

**Comment by illi-kun** [comment]
Also, breaking this issue in a bunch of issues will be much more useful. You found a lot of issues, and that's good, but it should be organized properly.

Thank you for understanding,

**Comment by Wuzzy2** [comment]
I don't think is correct. 200 batteries. Really? I think what is *meant* that it's some amount of batteries, with 200 *charges*. That's quite a difference.

**Comment by ZhilkinSerg** [comment]
> I don't think is correct. 200 batteries. Really? I think what is meant that it's some amount of batteries, with 200 charges. That's quite a difference.

The issue you reported earlier is resolved.
