### ISSUE TITLE
Pot duplicates after crafting clean water

### ISSUE THREAD

**Issue by LilVashya** [CleverRaven/Cataclysm-DDA#25110]
**Describe the bug**  
When crafting the clean water recipe and putting it into a wielded pot my character will drop the pot and create another in the process.
**To Reproduce**  
1. Wield a pot and put water into the pot.
2. Go near a fire and craft the clean water recipe then put the clean water into the pot.
3. Your character will drop the pot of clean water but still wield another.

**Expected behavior**  
Normally a character would try to prevent spilling the pot of clean water and drop the wielded item this however did not happen in this instance.

**Screenshots**  
https://imgur.com/a/Y36DyKB

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-30877-ga0b962a 
 - Graphics version: Tiles (MSX++DeadPeopleEdition) 
 - Mods loaded: More Survival Tools, Folding Parts Pack, Filthy Clothing, Makeshift Items, Mutant NPCs, NPC Traits, MXotto+ Cosmetics p10, No Fictional Guns, Simplified Nutrition, Extended Realistic Guns, No Acid Zombies. 
**Additional context**  
This build was 7742 last updated a day ago.
E.g. A link to a savegame that allows the issue to be reproduced.

**Comment by alanbrady** [comment]
This sounds like it was caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/25017 and was then fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/25098

7742 would have been the sweet spot between the two.  To verify, please try drinking from an aluminum can in your save game.  If it crashes then you need an updated version.

**Comment by LilVashya** [comment]
@alanbrady  Whenever I drank from a can it did crash so I guess this page is redundant then.

**Comment by alanbrady** [comment]
I don't think I tested cooking when using a spillable, so do please update your game and make sure there's still not some other issue I missed.

**Comment by LilVashya** [comment]
I updated it I will try this again and see if its still an issue.

**Comment by CoroNaut** [comment]
As of 0.c-31146-g4dd8ad1 I see this issue is fixed after testing myself.
