### ISSUE TITLE
Buggy NPC Companions won't move

### ISSUE THREAD

**Issue by Starlight-Grimmer** [CleverRaven/Cataclysm-DDA#31429]
NPC companions will no longer swap positions or be pushed away when updating to build 9121 or above, NPC will act normal otherwise ie will follow, guard ect. Issue does not persist with a new character.

How to reproduce: Create game pre-build 9121, get some NPC's to follow you, save and update to 9121 or above. Save game attached is from before update.

![Untitled](https://user-images.githubusercontent.com/51832190/59525572-970b0600-8ece-11e9-8a81-4b9c85ca99c9.png)
[#U2FyYWggUydKZXQ=.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3291535/U2FyYWggUydKZXQ.log)

**Comment by Zetsukaze** [comment]
Is the NPC you're interacting with sleeping? I see one with Zzz above his/her head

**Comment by Starlight-Grimmer** [comment]
nope, Jodie is hidden under the text box but she is fully awake. I've tried both while they're guarding and when they are following me.

**Comment by Zetsukaze** [comment]
Hmm, no idea, my NPCs worked fine on build 9139. FYI your log that you posted is not the save game =P

**Comment by Starlight-Grimmer** [comment]
how would I upload the save game? I tried but Github wouldn't accept the folder, should I zip it first?

**Comment by Zetsukaze** [comment]
Yeah zip it first zip the entire world folder

**Comment by Starlight-Grimmer** [comment]
here we go, this is on a file where the bug is active, I've also created a new NPC called Cedric 'Hex' Hale who isn't effected by the bug and can be moved around as they should be.
[Falkner.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3291860/Falkner.zip)

**Comment by Starlight-Grimmer** [comment]
I've tried looking into this some more, and it seems the NPC are no longer recognized as friendly, despite the fact they will still follow me around when asked to, I can't sort their armor. It also seems that they are showing up as neutral when I'm viewing all nearby creatures.

**Comment by SunshineDistillery** [comment]
I've seen something like this while debugging stuff due to inconsistencies with NPC dialogs.

An NPC can be a "friendly", which I think just means they have joined your faction, but they can also be just following you but not friendly--like an NPC you are guiding to a place for a mission.  Beyond that there can be dialog options that send you to the dialog menu, TALK_FRIENDLY, even if they aren't actually friendly, which causes weirdness.

**Comment by Lorith** [comment]
I had this happen when updating from a very old version.  You can use the debug menu to edit them into being fixed, or at least you could with my issue.  Debug menu > player > edit player/npc > select npc > following, if I recall correctly.  After that, you should be able to have them stay/follow again properly.  I can't check to be entirely certain since I already fixed mine, but I am pretty sure that was what I did.  Since you said your attempt didn't persist across save/load, I am not sure if it will fix it or not, but might be worth a try.

**Comment by Starlight-Grimmer** [comment]
tried to set them to following but that doesn't fix the issue even temporary.

**Comment by Starlight-Grimmer** [comment]
I've found a new fix, change "factions": [ { "id": "refugees" to "factions": [ { "id": "your_followers" in master.gsav, then for each NPC you need to change "faction_api_ver":2,"my_fac":"refugees" to "faction_api_ver":2,"my_fac":"your_followers", seems to persist through reloads, will update if it causes any further weirdness down the line though.

**Comment by SunshineDistillery** [comment]
I made this for debugging NPCs.  Change the file to .json and put it in one of your mod folders.  When you talk to an NPC a special dialog will show up for changing factions and attitudes.

Should you have further problems, it's a little easier than editing save files.

[TALK_DEBUG_NPC.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/3295435/TALK_DEBUG_NPC.txt)

**Comment by mlangsdorf** [comment]
Bug was caused by the blueprint_autocalc code corrupting NPC's faction pointers, and the corrupted pointers getting saved and reloaded.  The underlying bug has been fixed, but the corrupted save games remain.  SunshineDistillery has offered a work-around/mitigation, so I'm going to leave this issue up for a month and then close it.

**Comment by Ramza13** [comment]
Just bumping to say its been more than a month, time to close this?
