### ISSUE TITLE
Radiogenic doesn't heal enough to make getting irradiated a benefit

### ISSUE THREAD

**Issue by mkikt4743** [CleverRaven/Cataclysm-DDA#36115]
# Describe the bug

Radiogenic Mutation does not actually heal you enough to keep up with radiation damage

# Steps To Reproduce

1. Make a player with Radiogenic Mutation
2.Gain Irradiated (30)
3. Watch yourself take damage

# Expected behavior

Radiogenic should probably not allow you to take damage from rads, or heal faster than damage is taken

# Versions and configuration

 - OS: Windows 10
 - Game Version: 
 - Graphics version: Tiles
 - Mods loaded: dda, makeshift, crt_expansion

**Comment by Amoebka** [comment]
Irradiated (30) is pretty wild and probably shouldn't be desirable even with radiogenic.
What IS pretty dumb is that radiogenic doesn't remove/diminish stat penalties for being irradiated. In practice, you don't want to be even mildy (<10) irradiated with radiogenic, because the healing is negligible while the stat penalties are harsh.

**Comment by anothersimulacrum** [comment]
You shouldn't want to be irradiated, radiogenic or not. Radiogenic just makes it slightly less bad.

**Comment by arijust** [comment]
Shouldn't Radiogenic get renamed into Radiation Resistant and its description modified to be more correct in such case.

**Comment by Zireael07** [comment]
IIRC we have a Radiation Resistant mutation, too.

**Comment by anothersimulacrum** [comment]
No, because it doesn't make you radiation resistant, it makes you heal from radiation and keeps your healthy mod from going negative.
See [suffer.cpp L1051](https://github.com/CleverRaven/Cataclysm-DDA/blob/e667aa09a3eccf7464e909c1e3f193fe2188449f/src/suffer.cpp#L1051) (note that there's unreachable code on the line below that, 1062, that should be fixed).
Other code for it is at [suffer.cpp L1580](https://github.com/CleverRaven/Cataclysm-DDA/blob/e667aa09a3eccf7464e909c1e3f193fe2188449f/src/suffer.cpp#L1580) and [player.cpp L2232](https://github.com/CleverRaven/Cataclysm-DDA/blob/e667aa09a3eccf7464e909c1e3f193fe2188449f/src/suffer.cpp#L2232)

**Comment by arijust** [comment]
I see.
So Radiogenic is just slightly better Radiation Resistant, but it still doesn't make someone immune to it.

**Comment by kevingranade** [comment]
I'm not actually clear what the interaction is, but the Irradiated effect doesn't necessarily indicate how bad a dose you have.  It's only supposed to let you know you're irradiated at all, you need some other mechanism to tell you exactly how severe it is (which exists in the form of various tools in the game).

However, what I can say is that radiogenic is working as intended in that it provides healing at low doses of radiation (as well as clearing the radiation), but at higher doses the damage that radiation causes is much higher than the healing from radiogenic (up to 3x higher).
At 200 radiation, radiogenic heals one point of damage every 30 minutes.
At 201 radiation, you take one point of damage from radiation sickness on average every 50 minutes.
At 333 radiation, you take one point of damage every 30 minutes, healing and damage are balanced out.
At 500 radiation, you take one point of damage every 20 minutes, i.e. for every two points of healing you take 3 points of damage.
At 666 radiation, you take damage twice as fast as you heal it, i.e. one point of damage every 30 minutes.
At 1000 radiation, you take damage once every 10 minutes, so you take two points of damage every 30 minutes after the radiogenic healing..
