### ISSUE TITLE
Consumed something that was not food, drink or medicine/drugs error while opening the Eat menu

### ISSUE THREAD

**Issue by DillonSimeone** [CleverRaven/Cataclysm-DDA#40506]
# Describe the bug

If you're surrounded by mountains of loots and try to open the eat menu... The game thinks that you're trying to eat everything around you, and may crash! The more items you're surrounded with, the more likely it is for a crash to occur!

Debug message that's thrown for EACH items around you while opening the eat menu.

```
 DEBUG    : Consumed something that was not food, drink or medicine/drugs

 FUNCTION : time_duration Character::get_consume_time(const item&)
 FILE     : src/consumption.cpp
 LINE     : 1668
```

(I commented this on this issue, thinking that it was related. Might be a whole different thing by itself! https://github.com/CleverRaven/Cataclysm-DDA/issues/40268#issuecomment-627113341 )

# Steps To Reproduce

1. Load up my game, ignore all error messages.
2. Press `E` inside my car.
3. Despair at the flood of error messages, and possibly a crash! 

# Expected behavior

I'm not trying to eat everything! I'm just opening the eat menu, so... Instead of pretending that I ate everything around me, show me foods that I want to eat!

# Screenshots

![image](https://user-images.githubusercontent.com/21962421/81762104-9b45f780-9480-11ea-8d61-bc5b20712ad8.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2123-g10dbb76 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    More City Locations [cityside],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Arcana and Magic Items [Arcana],
    Graphical Overmap [Graphical_Overmap],
    Advanced Gear [adv_gear],
    Blaze Industries [blazeindustries]
]

# Additional context

Save: 
[Palmer Heights.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4613546/Palmer.Heights.zip)

Mods: 
[mods.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4613545/mods.zip)

**Comment by DillonSimeone** [comment]
Bad news! I just updated to Build #10659.

The first thing I did on game load? Pressed E in my car, and...

![image](https://user-images.githubusercontent.com/21962421/81811663-d88aa380-94d9-11ea-96c6-e345637b18ba.png)

Save and mods are still the same as up above. Crash and debug log attached to the end of this comment.

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2131-g3ac02c5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    More City Locations [cityside],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Arcana and Magic Items [Arcana],
    Graphical Overmap [Graphical_Overmap],
    Advanced Gear [adv_gear],
    Blaze Industries [blazeindustries]
]

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4621912/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4621913/debug.log)

**Comment by Ramza13** [comment]
It's not showing the message anymore right?  I think there were two separate things happening in this issue.  The first was the the messages which I hope I have fixed.  Looking at your crash.log the last bits are: 

05:21:55.110 ERROR : src/mapgen.cpp:324 [void mapgen_factory::check_consistency()] Mapgen house is not used by anything!
05:21:58.174 ERROR : src/item_factory.cpp:1352 [const itype* Item_factory::find_template(const itype_id&) const] Missing item definition: shot_pump
05:22:03.342 ERROR : src/item_contents.cpp:87 [void item_contents::combine(const item_contents&)] error: tried to put an item into a pocket that can't fit into it while loading.  err: No success
05:22:07.058 ERROR : src/item_factory.cpp:1352 [const itype* Item_factory::find_template(const itype_id&) const] Missing item definition: shot_buck
05:22:07.058 ERROR : src/item_factory.cpp:1352 [const itype* Item_factory::find_template(const itype_id&) const] Missing item definition: pistol_casing
05:22:07.066 ERROR : src/item_factory.cpp:1352 [const itype* Item_factory::find_template(const itype_id&) const] Missing item definition: pistol_ball
05:22:07.066 ERROR : src/item_factory.cpp:1352 [const itype* Item_factory::find_template(const itype_id&) const] Missing item definition: pistol_medium
05:22:07.074 ERROR : src/item_factory.cpp:1352 [const itype* Item_factory::find_template(const itype_id&) const] Missing item definition: tiny_pistol_jhp
05:22:07.074 ERROR : src/item_factory.cpp:1352 [const itype* Item_factory::find_template(const itype_id&) const] Missing item definition: pistol_tiny_target

This looks like pocket related data issues.  I am guessing some of your json mod or normal is wrong and causing issues.  It might be worth opening this as a new bug with the attached logs, or ask Korg to see if its a simple json fix in your save.

**Comment by DillonSimeone** [comment]
Oh, you're right, I ought clean those up. I've had those in my game for a few days, been ignoring it instead of cleaning my save file. 

I'll clean those out of my file, and see if this error still occur. I'll be surprised if that's the fix since it wasn't an issue until now!

**Comment by DillonSimeone** [comment]
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4627198/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4627200/debug.log)

I went though my save files and cleaned them all up. The crash is still occurring in my car. Strange.

```
Backtrace emission took 0 seconds.
src/item_factory.cpp:1352 [const itype* Item_factory::find_template(const itype_id&) const] Missing item definition: shot_pump
01:09:29.420 ERROR : src/generic_factory.h:404 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = ter_t]] invalid terrain id "hdhatch"
01:09:31.136 ERROR : src/generic_factory.h:404 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = ter_t]] invalid terrain id "hdhatch"
01:09:37.184 ERROR : src/generic_factory.h:404 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = ter_t]] invalid terrain id "hdhatch"
01:09:37.184 ERROR : src/generic_factory.h:404 [int_id<T> generic_factory<T>::convert(const string_id<T>&, const int_id<T>&) const [with T = ter_t]] invalid terrain id "hdhatch"
```

I tried removing the old mod, [AdvancedGear-CDDA-Mod-master](https://github.com/Lorith/AdvancedGear-CDDA-Mod) from my save. Crash is still happening when I eat in my vehicle. Hmm.

Making a new issue on this.
