### ISSUE TITLE
Camp upgrades no longer scrollable

### ISSUE THREAD

**Issue by Polubing** [CleverRaven/Cataclysm-DDA#45820]
# Describe the bug

When selecting from the list of missions/upgrades at camp center, list is non-scrolling if larger than screen resolution supports, leading to selected-option-cursor going off-screen. In screenshots shown below, the camp chores, cut trees, clear forest, and forage for plants camp missions are not shown but are all able to be selected, just not shown on screen, while showing up in the mission description section of the ui. Ran the game in windowed mode and there was _some_ scrolling, but it did not go all the way down and cut trees, clear forest, and forage for plants camp missions are not shown but are all able to be selected.

# Steps To Reproduce

Progress faction camp, and either have a full screen of options that go beyond the ui, or run game in windowed mode at small resolution so that options no longer fit on screen.

# Expected behavior

Expected for cursor to be able to stay in boundaries of ui while selecting the last few camp missions, not go off screen.

# Screenshots

In screenshots shown below, the camp chores, cut trees, clear forest, and forage for plants camp missions are not shown but are all able to be selected, just not shown on screen, while showing up in the mission description section of the ui.

![image](https://user-images.githubusercontent.com/61110588/101229620-c1262a00-3666-11eb-8336-d821d288bc82.png)
![image](https://user-images.githubusercontent.com/61110588/101229636-d9964480-3666-11eb-8124-78b6895ad803.png)

Ran the game in windowed mode and there was _some_ scrolling, but it did not go all the way down and cut trees, clear forest, and forage for plants camp missions are not shown but are all able to be selected.

![image](https://user-images.githubusercontent.com/61110588/101229926-380ff280-3668-11eb-9388-d7d6d4e699b8.png)
![image](https://user-images.githubusercontent.com/61110588/101229935-43631e00-3668-11eb-9f48-603eb3c71376.png)
![image](https://user-images.githubusercontent.com/61110588/101229944-4d851c80-3668-11eb-9e90-6d6715c866eb.png)
![image](https://user-images.githubusercontent.com/61110588/101229952-54139400-3668-11eb-9024-1b838bb13188.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-8007-gf58e7a4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

This isn't a crash, but I have backed-up this save and zipped it up. 
[Bonners Ferry.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5646288/Bonners.Ferry.zip)

**Comment by Polubing** [comment]
Still happening with #11221

**Comment by PatrikLundell** [comment]
The problem looks like the one fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/45399 which was merged 12 days ago. I tried the save on my local copy of the game that has a baseline newer than the merge, and it scrolled correctly when I compressed the game window enough to require scrolling.

**Comment by Polubing** [comment]
Perhaps the bug is only happening when there are a requisite overflow of camp missions, not just being limited by screen resolution. I fresh installed the launcher on Dec. 3rd, and my current save was started a couple days after that.

As of 0.E-8036-g966ab2d this is still an issue
![image](https://user-images.githubusercontent.com/61110588/101419315-5cacda00-38b5-11eb-8f40-80abb26b400e.png)

**Comment by Joar80** [comment]
This is happening on the fabrication workshop screen as well. Scrollbar goes off screen at the bottom as well as the lowest three items. 
Playing on 1440p fullscreen.

- OS: Windows 10
    - OS Version: 10.0 2004
- Game Version: 0.E-8079-g47fa519 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex]
]

**Comment by PatrikLundell** [comment]
Hm, yes, after some experimentation I was able to replicate the problem with 0.E-8079-g47fa519 [64-bit], after the initial attempts not resulting in any issues. It appears there are some window sizes that causes the problem to manifest itself, while it works correctly at others.
