### ISSUE TITLE
Pristine MRE not sealed as of version 2022-01-02 - 1804

### ISSUE THREAD

**Issue by BurgundyLouvalle** [CleverRaven/Cataclysm-DDA#53979]
### Describe the bug

Pristine MREs do not spawn as sealed and contents that are not individually sealed within begin to rot immediately(or have already rotted away).

### Steps to reproduce

1. create new world
2. create character with the overrun scenario(starts you in a military warehouse full of pristine MREs)
3.  go to MREs in warehouse and see that they are indeed not sealed and their unsealed contents are rotting.

### Expected behavior

Pristine MREs should start as sealed as they are expected to have a five year shelf life in extreme conditions.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: acacbb1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Extra Mutated Scenarios [extra_mut_scens],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Graphical Overmap [Graphical_Overmap],
    Tankmod: Revived [Tankmod_Revived]
]

**Comment by Sirbab** [comment]
It's been happening at least since 2021-12-31-2003, which is when my world was made.

**Comment by BurgundyLouvalle** [comment]
I did some more looking at the files and I think I found the issue.  the container needs to be full for it to be sealed(sealable?) and since the last edit to the mre changed the contents it meant the MRE had free space.

The cheese spread also failed to spawn for some reason.

I fixed the cheese spread not spawning by taking the following lines:

{
        "distribution": [
          { "item": "can_cheese", "charges": 1, "container-item": "mre_bag_small", "sealed": true },
          { "item": "spread_peanutbutter", "charges": 1, "container-item": "mre_bag_small", "sealed": true }
        ]
      },

and adjusting them to

     { "item": "can_cheese", "charges": 10, "container-item": "mre_bag_small", "sealed": true },
     { "item": "spread_peanutbutter", "charges": 1, "container-item": "mre_bag_small", "sealed": true },

The second issue is that when a container is not full it cannot have a seal, this affected the overall mre bag as well as the cheese spread.

I fixed the cheese spread by incresing its count to ten charges (reflected in the above lines) and then fixed the overall mre by changing th pocket size of an "mre_package" to 2974 ml

**Comment by ahmedcharles** [comment]
Perhaps there should be a warning in the debug log for items that are specified as spawning sealed but aren't specified as spawning full?

**Comment by Alex-Folts** [comment]
> I did some more looking at the files and I think I found the issue.

True, it was noted in coments for https://github.com/CleverRaven/Cataclysm-DDA/pull/53552

**Comment by Sirbab** [comment]
Making your changes @BurgundyLouvalle the cracker bag is still not full btw, 0.125 l too large, either there needs to be two crackers in the bag (assuming the bag needs to be full), crackers need to have their volume doubled (bleh), a different bag needs to be used for the cracker, or the better alternative is un-linking bag fullness from whether it's sealed or not.

**Comment by BurgundyLouvalle** [comment]
the cookies are covered by the main bag seal.  but thanks for the catch on crackers.

**Comment by Sirbab** [comment]
> 

One more thing, i think your MRE package volume is anagramed, it should be 2749ml to my count, which after spawning a Mil_Base tile results in it being sealed, which the previous value you used was not. 
![image](https://user-images.githubusercontent.com/1490991/147891845-39da1208-e79b-40d7-b583-0aa1c8d42577.png)

**Comment by BurgundyLouvalle** [comment]
ok, the new size for the bag with 2 cracker charges is 3099 ml.  Also, @Sirbab , I checked the fhreshness and even though the cookies and other stuff don't say sealed fresh, the overarching bag's seal will still prevent spoilage as they will remain at their starting shelf life.

**Comment by BurgundyLouvalle** [comment]
is there cheese spread in your bags?

**Comment by Sirbab** [comment]
Yup 
![image](https://user-images.githubusercontent.com/1490991/147891866-23f0392c-8e81-4500-9f56-b3f70e4b67fc.png)

**Comment by BurgundyLouvalle** [comment]
peanut butter spread is missing

**Comment by Sirbab** [comment]
> peanut butter spread is missing

Ah, then that was probably a syntax error on my part with your change.  Good eye.

**Comment by BurgundyLouvalle** [comment]
Here is the code for the mre_contents

  "entries": [
      { "group": "mre_entrees", "container-item": "mre_bag_small" },
      { "item": "heatpack" },
      { "item": "can_cheese", "charges": 10, "container-item": "mre_bag_small", "sealed": true },
      { "item": "spread_peanutbutter", "charges": 1, "container-item": "mre_bag_small", "sealed": true },
      { "item": "crackers", "charges": 2, "container-item": "mre_bag_small", "sealed": true },
      { "group": "mre_accessory_pack" },
      { "item": "mre_bag", "contents-group": "mre_dessert_pack", "sealed": true }
    ]

**Comment by Sirbab** [comment]
Should the MRE always spawn with both peanut butter and cheese? This seems intentionally random one vs the other.

**Comment by Sirbab** [comment]
![image](https://user-images.githubusercontent.com/1490991/147892100-c5cfe4f9-0c15-46b6-9321-d7e8099168c3.png)
It doesn't seem to be the case as per https://m.goarmy.com/soldier-life/fitness-and-nutrition/components-of-nutrition/meals-ready-to-eat.m.html

**Comment by Sirbab** [comment]
Okay, i have it in a workable state, as in either type spawns sealed, either cheese or peanut butter.  But the problem is that increasing the number of cheese spread from 1 to 8 (the max the bag can hold) increases the caloric value of a cheese MRE by 623 calories.  Now, while this works as a really quick and dirty fix, it's undesirable from a balance or sense perspective.
One of the following needs to happen i think, in my opinion of ascending desirability.
A: The caloric value of cheese spread needs to be cut by a factor of 8, and crafting recipes adjusted.
B: A different bag with an 1/8 the volume is specifically made to contain the cheese spread, retaining balance, but adding item clutter imo.
C: Bags need to be able to be "sealed" in the games eyes even with empty volume (really though this is strange that it does this, what chip bag doesn't have air as a cushion?).

**Comment by BurgundyLouvalle** [comment]
yeah, thats why i kept both, as you either get 500 calories of cheese or 190 calories of peanut butter, honestly you can just say the army started putting both in MREs  some time back and leave it at that as the other solutions require way to much work for a quick and dirty fix
