### ISSUE TITLE
Mutation issues regarding instability and threshold breaking.

### ISSUE THREAD

**Issue by Sinistrem** [CleverRaven/Cataclysm-DDA#57716]
### Describe the bug

1. There is a high chance of getting negative mutations, even at extremely low (sub 600) instability levels.
2. It is possible to break threshold by rolling a non-threshold mutation.

### Steps to reproduce

1. Gain high amount of mutagen (i.e. by using mutagenic catalyst).
2.  Gain high amount of targeted mutagen (i.e. feline mutagenic primer) / overdose on it to test threshold break.
3.  Keep instability below 800 or even lower by using debug menu.
4. Pass time.

### Expected behavior

![155929859-ce9490f3-73ff-4101-a49b-eb8cacbb7659](https://user-images.githubusercontent.com/104842796/168457004-411e8a8f-eb95-4104-9d57-bba0979682e3.png)

According to Maleclypse:

> Mutations are given completely subjective point values.  The most important factor is that mutations that adversely affect a character are given a negative point value, or positive for beneficial mutations.  The chance of obtaining a positive or negative mutation varies based on Instability (a counter that increases by a default of 100 when a mutation is gained or lost and decays by 1 per in-game day by default).  0 point mutations will always have a 10% chance of appearing.  There is a 90% chance to obtain a good mutation until approximately 800 Instability.  There is an equal chance (45% each) of obtaining a good or bad mutation at approximately 2800 Instability.  There is an approximately 70% chance of obtaining a bad mutation at 10000 Instability, which will be the cap after a current test phase where it is capped at 8000.
> 
> make a bug report please
> 
> the markdown I listed above is in the game_balance.md and is in the same PR as the graph you showed.  I can't reconcile the two of them together with you getting lots of bad mutations pre 800 instability.

As far as I'm aware, the only way to roll a negative mutation below 800 is to roll a positive mutation that requires a negative as a prerequisite, in which case you will get that negative instead. Out of all the negatives I've got only carnivore fits that description, and I have never crossed a 800 instability threshold. My latest two negatives, Strong Scent and Hates Water appeared back to back at about 500 instability.

Additionally I've broken the threshold by getting a non threshold mutation, which should not be possible. As far as I'm aware, you break threshold by overdosing on targeted mutagen and rolling a post threshold mutation. I've broken it by getting Lynx Fur, a non threshold mutation (see screenshots).

I am also adding a zip with my save file in case that helps to track down the issue.

### Screenshots

![Thresh break](https://user-images.githubusercontent.com/104842796/168457279-03fbf062-9c00-41c7-9211-dc8089de2ef5.png)

### Versions and configuration

- WIndows 10
- Latest experimental -b03e041
- Tiles
- English
- Mods: dda, no npc food, no_fungal_growth, package_bionic_professions, blazeindustries, generic_guns.

### Additional context

Save link (too large to attach here): https://mega.nz/file/jkEVTAqS#r2-Xx69K4A3CntlMiHW3u4O8e2jzSc-dmC93GYESN84

**Comment by Sinistrem** [comment]
I've also just noticed that breaking the threshold didn't reduce the targeted mutagen count as it supposed to. As far as I'm aware, successfully crossing the threshold should reduce the targeted mutagen count by 1500, yet this is how much of it I have. Given that 2500 is the maximum possible amount, it is obvious that something is amiss.
![image](https://user-images.githubusercontent.com/104842796/168459172-1e4b6512-1d77-47c0-aa53-58261939d709.png)

**Comment by Sinistrem** [comment]
Testing was done with overdose / close to overdose on targeted vitamins due to trying to break the threshold. I wasn't specifically trying to have a very large amount of generic mutagen, but from what I can gather generic mutagen merely initiates mutation and dictates it's duration, stopping when it drops too low.

**Comment by Stadler76** [comment]
This might have been addressed by #58803.

**Comment by Sinistrem** [comment]
From my limited C understanding those code changes are just an additional check to prevent gaining mutations unrelated to the mutagen you've injected yourself with, which was an annoying, but ultimately unrelated issue. I'll check it out later (haven't played in a month or so), but I doubt it is fixed.

**Comment by Stadler76** [comment]
> From my limited C understanding those code changes are just an additional check to prevent gaining mutations unrelated to the mutagen you've injected yourself with, which was an annoying, but ultimately unrelated issue. I'll check it out later (haven't played in a month or so), but I doubt it is fixed.

Well, at least it partially fixed this issue:
> 2. It is possible to break threshold by rolling a non-threshold mutation.

The other part is hopefully fixed by PR #58832.
