### ISSUE TITLE
Item qt_steel_lump has no spawn or recipe

### ISSUE THREAD

**Issue by snipercup** [CleverRaven/Cataclysm-DDA#58033]
### Describe the bug

The item qt_steel_lump was added in #56300, but without spawn or recipe. In other words, there's no way to acquire the item. 

### Steps to reproduce

1. Look for qt_steel_lump on github
2. Observe results without any spawn

### Expected behavior

Able to find/craft it in game:
- recipe
- deconstruction of furniture/car parts
- item spawn (steel mill for example)

### Versions and configuration

- experimental

**Comment by Maleclypse** [comment]
@Drew4484

**Comment by Drew4484** [comment]
This isn't something you should need for recipes, the proper solution for any tempered item should be either crafting it from lower grades of steel or by upgrading an existing medium steel item. The chunk and lump of tempered and hardened steel should be byproducts of deconstruction/destruction of tempered or hardened items, respectively.

**Comment by PatrikLundell** [comment]
So they are intended to just be garbage items fooling the player into thinking they're valuable?

If the missing deconstruction recipes that would yield them was added, there ought to be recipes to downgrade them into usable versions.

**Comment by Shados** [comment]
@Drew4484 as it stands, `qt_steel_chunk` is required to *repair*/reinforce tempered steel gear, but is unobtainable in game. What's the intended repair/reinforce path for these items...?

**Comment by Drew4484** [comment]
> @Drew4484 as it stands, `qt_steel_chunk` is required to *repair*/reinforce tempered steel gear, but is unobtainable in game. What's the intended repair/reinforce path for these items...?

The IRL options for repairing tempered steel are to do an extremely precise weld just below the tempering point of the steel, which we don't have a good way to simulate. The other option is to dismantle and reforge the item.

A chunk of tempered steel is useless on its own unless you are cutting away a damaged section and using the above welding process to attach it.

**Comment by Drew4484** [comment]
This should be resolved by #59682

**Comment by snipercup** [comment]
> This should be resolved by #59682

I don't see how it does. qt_steel_lump isn't mentioned in the changed files
![image](https://user-images.githubusercontent.com/50166150/182028977-92f7412a-f111-4fc2-b9bd-996bb5e662f2.png)

**Comment by Drew4484** [comment]
> > This should be resolved by #59682
> 
> I don't see how it does. qt_steel_lump isn't mentioned in the changed files
> ![image](https://user-images.githubusercontent.com/50166150/182028977-92f7412a-f111-4fc2-b9bd-996bb5e662f2.png)
> 

It provides an option to repair tempered steel without adding lumps, since those aren't a reasonable item.

**Comment by snipercup** [comment]
> > > This should be resolved by #59682
> > 
> > 
> > I don't see how it does. qt_steel_lump isn't mentioned in the changed files
> > ![image](https://user-images.githubusercontent.com/50166150/182028977-92f7412a-f111-4fc2-b9bd-996bb5e662f2.png)
> 
> It provides an option to repair tempered steel without adding lumps, since those aren't a reasonable item.

I don't see how that's a solution. qt_steel_lump still isn't used. Can't you remove it from the game if it isn't used anyway?

**Comment by Drew4484** [comment]
> > > > This should be resolved by #59682
> > > 
> > > 
> > > I don't see how it does. qt_steel_lump isn't mentioned in the changed files
> > > ![image](https://user-images.githubusercontent.com/50166150/182028977-92f7412a-f111-4fc2-b9bd-996bb5e662f2.png)
> > 
> > 
> > It provides an option to repair tempered steel without adding lumps, since those aren't a reasonable item.
> 
> I don't see how that's a solution. qt_steel_lump still isn't used. Can't you remove it from the game if it isn't used anyway?

It is used, you make [wire](https://nornagon.github.io/cdda-guide/#/item/qt_wire) from it.

**Comment by snipercup** [comment]
> > > > > This should be resolved by #59682
> > > > 
> > > > 
> > > > I don't see how it does. qt_steel_lump isn't mentioned in the changed files
> > > > ![image](https://user-images.githubusercontent.com/50166150/182028977-92f7412a-f111-4fc2-b9bd-996bb5e662f2.png)
> > > 
> > > 
> > > It provides an option to repair tempered steel without adding lumps, since those aren't a reasonable item.
> > 
> > 
> > I don't see how that's a solution. qt_steel_lump still isn't used. Can't you remove it from the game if it isn't used anyway?
> 
> It is used, you make [wire](https://nornagon.github.io/cdda-guide/#/item/qt_wire) from it.

But you can't get qt_steel_lump. It doesn't spawn and you can't get it trough disassembly or deconstruction. Your PR doesn't change that so this issue remains open.

**Comment by RenechCDDA** [comment]
/confirmed

#59682 removed the last use of `qt_steel_lump` (making wire) and - insofar as I can tell - it cannot be acquired or used in any way.  This also applies to `qt_steel_chunk` under the same circumstances.
