### ISSUE TITLE
Game crash after using Advanced Inventory Manager

### ISSUE THREAD

**Issue by MrCumberdale** [CleverRaven/Cataclysm-DDA#62606]
### Describe the bug

There is a chance of the game crashing right after using the Advanced Inventory Manager, of which the interface won't leave the screen right after quitting the menu with Escape; the character can move, use different menus and open the Advanced Inventory Manager again and use it, and right after doing any of those actions the menu might leave as intended, but in some cases it causes the game to crash.

### Steps to reproduce

- Stand near a pile of objects
- Open the Advanced Inventory Manager ( / )
- Move objects around a couple times
- Exit the menu using Escape

### Expected behavior

 Game might continue as usual, as it may leave the visual of the menu you tried to escape still on screen. It's a gamble.

### Screenshots

![image](https://user-images.githubusercontent.com/119970960/206004908-1ae40b7a-8799-40ca-9ef8-86ed6a55dd9a.png)

### Versions and configuration

- OS: Windows 10
- Game Version: Experimental 1894579
- World mods: ![image](https://user-images.githubusercontent.com/119970960/206008043-1a6c9f1f-5591-43aa-a0d2-fd32959a4b69.png)

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10169806/crash.log)

**Comment by andrei8l** [comment]
Your steps to reproduce appear to be way off, based on your screenshot. It looks like you did this:
1. Open the AIM then move one small item to an adjacent square
2. Close the AIM
3. AIM stays open due to #62551
4. Without passing a turn, while the AIM is still open, you started disassembling a kevlar panel
5. Crash

If that's the case, then this should be fixed with #62560. Please try again once the [latest release](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-12-06-2016) finishes building

**Comment by MrCumberdale** [comment]
Left out debug.log
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/10170041/debug.log)
Save file is 35 MB, which is 10 MB over the upload limit

**Comment by MrCumberdale** [comment]
> Your steps to reproduce appear to be way off, based on your screenshot. It looks like you did this:
> [...]
> 4. Without passing a turn, while the AIM is still open, you started disassembling a kevlar panel
> 5. Crash

Happened for different actions, in this case it crashed because I was trying to disassemble Kevlar but it has happened for walking and hauling objects.
 
> If that's the case, then this should be fixed with #62560. Please try again once the [latest release](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-12-06-2016) finishes building

I'll update the game tomorrow to check, thx

**Comment by intergalacticdata** [comment]
Just a confirmation that this was still crashing in Monday's build on mass move. (12/5/22)

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 11 (bullseye); Release: 11; Codename: bullseye; 
- Game Version: ab877e4bed0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by andrei8l** [comment]
> Just a confirmation that this was still crashing in Monday's (12/5/22) build on mass move of a single item type.
>     * Game Version: [ab877e4](https://github.com/CleverRaven/Cataclysm-DDA/commit/ab877e4bed06df81d209266a5ae34be432baca2d) [64-bit]

The build you linked is older than both this bug report and the fix.

**Comment by TealcOneill** [comment]
@GuardianDll This was almost certainly fixed by #62560.
