### ISSUE TITLE
Cant pass through broken car seats and broken trunks

### ISSUE THREAD

**Issue by KHeket** [CleverRaven/Cataclysm-DDA#70555]
### Describe the bug

Cant pass through broken car seats and broken trunks

### Attach save file

N/A

### Steps to reproduce

Spawn/find broken can with trunks and seats, as example, shooting brake, try to cross trunk/seat - see no way. My character is 185 cm height

### Expected behavior

To have all working as intended 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 502fa46 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by MrHrulgin** [comment]
It was theoretically fixed with #70393. Update and see if it's working for you?

**Comment by KHeket** [comment]
> It was theoretically fixed with #70393. Update and see if it's working for you?

I played at the
[Cataclysm-DDA experimental build 2023-12-31-0337](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-12-31-0337) 
So https://github.com/CleverRaven/Cataclysm-DDA/pull/70393 didn't fix that

**Comment by fairyarmadillo** [comment]
Confirmed. The way the check for a broken part is set up is confusing to me. When I fixed broken CARGO_PASSABLE parts being impassible, I accidentally made broken CARGO parts impassible. I will put in a fix for this in the morning.
