### ISSUE TITLE
Add NPC sleep zones or a follower flag that would force them to sleep nearby

### ISSUE THREAD

**Issue by AideeAmei** [CleverRaven/Cataclysm-DDA#78392]
### Is your feature request related to a problem? Please describe.

My main character has a base near forest and she had to cut down hundreds of trees so she could build a graveyard with hundreds of graves because each follower she got one night decided they're so sleepy they need to go to a nearest bed while on a night raid and got their insides eviscerated by horrors because they found sleeping in an infested house safer than sleeping in the van that even has a bed.

One time, a follower decided to sleep on a bench near race track, where literally dozen zombies just wondered around. Damn, they had to be really tired to lay there.

### Solution you would like.

Being able to set up a zone the followers would be forced to sleep in when tired.

### Describe alternatives you have considered.

Another great way how to deal with it (maybe even better one) would be to make a flag in follower rules that would prevent them from requiring too much privacy when trying to sleep. They got an empty bed with a shark pillow and a teddy bear and a mini-fridge with lemonade next to it 4 tiles away from the player character who is silently reading their electronics book. This shouldn't be an issue.

The flag could be enabled by default, because running off into the night is always a stupid idea. No matter how hard the floor you have to sleep on is.

**Comment by RenechCDDA** [comment]
Micromanaging is never the answer. See #71865

If there are issues with the implementation they should be fixed. Asking the player to decide for them is patently unwanted.

**Comment by AideeAmei** [comment]
Well, yes, there is an issue with the implementation. People keep going to sleep in a strange house deep in zombie territory. If the NPCs I meet had been doing this all along, how did they even survive all that time until they spawned? It's inconsistent and mind boggling especially when I have a bed at ready literally a few tiles away. And I know followers don't ignore vehicle beddings, I saw them using the bed before. I think they even borrowed a vibrator on an occasion.

**Comment by Zireael07** [comment]
@AideeAmei Comment in the linked issue instead of duplicating essentially the same discussion

**Comment by AideeAmei** [comment]
I didn't notice the link, obviously. And I searched issues before creating this and didn't find it either, because I was looking for open ones, since it's still a problem.
