### ISSUE TITLE
Crash when touching a particular vehicle

### ISSUE THREAD

**Issue by Pheared-Phantom** [CleverRaven/Cataclysm-DDA#84222]
### Describe the bug

[Main-trimmed.tar.gz](https://github.com/user-attachments/files/24203522/Main-trimmed.tar.gz)

### Attach save file

Attached Below

### Steps to reproduce

Touch the vehicle to trigger crash

### Expected behavior

Not crashing

### Versions and configuration

Windows 10
Version: https://github.com/CleverRaven/Cataclysm-DDA/releases?q=prerelease%3Afalse&expanded=true

### Additional context

[crash.log](https://github.com/user-attachments/files/24203561/crash.log)
[debug.log](https://github.com/user-attachments/files/24203562/debug.log)

[Main-trimmed.tar.gz](https://github.com/user-attachments/files/24203567/Main-trimmed.tar.gz)

**Comment by Pheared-Phantom** [comment]
Sorry if i did this wrong. Its my first bug report

**Comment by PatrikLundell** [comment]
Failed to repeat. I tried to: Grab, examine, and interact with both vehicles without any issues.

You're not doing a stellar job in the bug reporting department, I'm afraid:
- The attached file is supposed to go into the dedicated section. That's not a big issue, as humans can find it even if it's placed elsewhere.
- The reproduction description is poor:
  - There is no such thing as "touch" in the game. You should have described what interaction you were trying to use.
  - The description didn't specify which vehicle, nor where it was to be "touched".
- The Versions and configuration section data is filled out incorrectly. The normal way to do that is to use the game's functionality to capture the info to the clipboard and then paste it into this section. A link to the page where the release was downloaded from at some unspecified time in the past isn't much of an indication of which version was downloaded, and that doesn't say anything about the configuration, in particular the (obsolete) mods used.

With the hope that the next report will be in better shape.

**Comment by Pheared-Phantom** [comment]
> Failed to repeat. I tried to: Grab, examine, and interact with both vehicles without any issues.
> 
> You're not doing a stellar job in the bug reporting department, I'm afraid:
> 
> * The attached file is supposed to go into the dedicated section. That's not a big issue, as humans can find it even if it's placed elsewhere.
> * The reproduction description is poor:
>   
>   * There is no such thing as "touch" in the game. You should have described what interaction you were trying to use.
>   * The description didn't specify which vehicle, nor where it was to be "touched".
> * The Versions and configuration section data is filled out incorrectly. The normal way to do that is to use the game's functionality to capture the info to the clipboard and then paste it into this section. A link to the page where the release was downloaded from at some unspecified time in the past isn't much of an indication of which version was downloaded, and that doesn't say anything about the configuration, in particular the (obsolete) mods used.
> 
> With the hope that the next report will be in better shape.

I said touch because there was no action performed, as a human could inquire. I simply walked up to the vehicle (pressed to corresponding keys in order to move the sprite in the direction of the closest vehicle which a human could deduce would be the one causing an issue due to the only other one having indications of being interacted with). However I provided the debug and crash log which may give some valuable insight.
I did not see any sort of direction for providing the version. So I did the next best thing and gave the link to the download.

I went back to the vehicle and it would seem the issue is no longer occurring. Which is good, but strange. Anyways I guess the issue is resolved?

**Comment by mqrause** [comment]
The crash log points to npc pathfinding through or into a vehicle being the cause of the crash. So probably not resolved, but I'm not sure what we can do without reliable reproduction steps.

**Comment by PatrikLundell** [comment]
The problem with the reproduction description is that it's sufficient when the error is reproduced, but leaves the investigator puzzled when it isn't.

Anyway, you produce the info about the game from an entry called "Generate game report", which should be right next to the "Generate minimized save archive" entry you might have used to generate the save. I'm not quite sure how you reach these via the UI, because I've bound the debug menu to a key, and get all of it through that.
In my case I can get it via <ESC>, Debug menu (at the end of the MAIN MENU), Info..., and then the Generate entries at the end.
This is what the report can look like:

- OS: Windows
    - OS Version: 10.0.26200.7462 (25H2)
- Game Version: cdda-experimental-2025-10-09-0624-1083-gec6109f426 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    PALU [PALU]
]

**Comment by Pheared-Phantom** [comment]
> The crash log points to npc pathfinding through or into a vehicle being the cause of the crash. So probably not resolved, but I'm not sure what we can do without reliable reproduction steps.

That would make sense because when i checked the seconds time, i left the npc home

**Comment by Pheared-Phantom** [comment]
> The problem with the reproduction description is that it's sufficient when the error is reproduced, but leaves the investigator puzzled when it isn't.
> 
> Anyway, you produce the info about the game from an entry called "Generate game report", which should be right next to the "Generate minimized save archive" entry you might have used to generate the save. I'm not quite sure how you reach these via the UI, because I've bound the debug menu to a key, and get all of it through that. In my case I can get it via , Debug menu (at the end of the MAIN MENU), Info..., and then the Generate entries at the end. This is what the report can look like:
> 
> * OS: Windows
>   
>   * OS Version: 10.0.26200.7462 (25H2)
> * Game Version: cdda-experimental-2025-10-09-0624-1083-gec6109f426 [64-bit]
> * Graphics Version: Tiles
> * Game Language: System language []
> * Mods loaded: [
>   Dark Days Ahead [dda],
>   Disable NPC Needs [no_npc_food],
>   Portal Storms Ignore NPCs [personal_portal_storms],
>   PALU [PALU]
>   ]


Game Report:
- OS: Windows
    - OS Version: 10.0.19045.6466 (22H2)
- Game Version: 78fd6e3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    Extra Mutated Scenarios [extra_mut_scens],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife]
]

**Comment by Pheared-Phantom** [comment]
If you need anything else, I'll be happy to help. The crash did trigger again when I had the npc follow me

Extra Info:
I had him guard the area and there was no issue when I entered the vehicle (makes sense if it is pathfinding issue)
Entered the vehicle while he was guarding and had him follow me, the crash happened after i pressed "." to make time pass. It was stable until I did so
